name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify Windows SDK tools
        run: |
          where rc.exe
          where link.exe
          rustc -Vv
          cargo -V

      - name: Env for verbose builds
        run: |
          echo "RUST_BACKTRACE=1" >> $Env:GITHUB_ENV
          echo "CARGO_TERM_COLOR=always" >> $Env:GITHUB_ENV

      - name: Generate card sprite (CC0/PD)
        run: |
          cargo run -p xtask -- gen-cards --card-w 224 --card-h 312

      - name: Upload generated sprite
        uses: actions/upload-artifact@v4
        with:
          name: cards-sprite
          path: res/cards.png

      - name: Build (release)
        run: cargo build --release --locked

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: klondike-windows-x86_64
          path: target/x86_64-pc-windows-msvc/release/klondike.exe
